import { defineConfig } from 'orval'

export default defineConfig({
  quantBacktest: {
    input: {
      target: 'http://localhost:3080/api/openapi.json',
    },
    output: {
      mode: 'tags-split',
      target: 'src/api/generated',
      schemas: 'src/api/generated/schemas',
      client: 'react-query',
      headers: true,
      override: {
        mutator: {
          path: 'src/api/mutator.ts',
          name: 'customInstance',
        },
        query: {
          useQuery: true,
          useMutation: true,
          useInfinite: true,
          useInfiniteQueryParam: 'page',
        },
        header: () =>
          '// @ts-nocheck\n// This file is auto-generated by orval. Do not edit manually.\n',
      },
    },
    hooks: {
      afterAllFilesWrite: 'prettier --write',
    },
  },
})
