/**
 * Industry Tree API hooks (manual, not generated by orval)
 *
 * Provides hooks for fetching hierarchical industry data for cascading selection:
 * - EM (EastMoney): Flat structure, 86 industries
 * - SW (Shenwan): Hierarchical L1 -> L2 -> L3
 */

import { useQuery } from "@tanstack/react-query"
import type { UseQueryOptions, UseQueryResult, QueryKey } from "@tanstack/react-query"
import { customInstance } from "./mutator"

export interface IndustryTreeItem {
  name: string
  level: number
  stock_count: number
  has_children: boolean
}

export interface IndustryTreeResponse {
  system: string
  parent: string | null
  items: IndustryTreeItem[]
}

export interface GetIndustryTreeParams {
  system?: 'sw' | 'em'
  parent?: string
  level?: number
}

/**
 * Fetch industry tree data
 */
export const getIndustryTree = (
  params?: GetIndustryTreeParams,
  signal?: AbortSignal,
) => {
  return customInstance<IndustryTreeResponse>({
    url: `/api/v1/universe/industries/tree`,
    method: "GET",
    params,
    signal,
  })
}

export const getIndustryTreeQueryKey = (params?: GetIndustryTreeParams) => {
  return [`/api/v1/universe/industries/tree`, ...(params ? [params] : [])] as const
}

export const getIndustryTreeQueryOptions = <
  TData = IndustryTreeResponse,
  TError = unknown,
>(
  params?: GetIndustryTreeParams,
  options?: {
    query?: Partial<UseQueryOptions<IndustryTreeResponse, TError, TData>>
  },
) => {
  const { query: queryOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getIndustryTreeQueryKey(params)

  const queryFn = ({ signal }: { signal?: AbortSignal }) =>
    getIndustryTree(params, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    IndustryTreeResponse,
    TError,
    TData
  > & { queryKey: QueryKey }
}

/**
 * Hook to fetch industry tree data
 */
export const useGetIndustryTree = <
  TData = IndustryTreeResponse,
  TError = unknown,
>(
  params?: GetIndustryTreeParams,
  options?: {
    query?: Partial<UseQueryOptions<IndustryTreeResponse, TError, TData>>
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getIndustryTreeQueryOptions(params, options)

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey
  }

  query.queryKey = queryOptions.queryKey

  return query
}
