"""initial_schema

Revision ID: 3f56b2b929aa
Revises: 
Create Date: 2025-12-18 14:44:27.773100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3f56b2b929aa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adjust_factor',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('divid_operate_date', sa.Date(), nullable=False),
    sa.Column('fore_adjust_factor', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('back_adjust_factor', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('adjust_factor', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('code', 'divid_operate_date')
    )
    op.create_index('idx_adjust_factor_code', 'adjust_factor', ['code'], unique=False)
    op.create_index('idx_adjust_factor_date', 'adjust_factor', ['divid_operate_date'], unique=False)
    op.create_table('asset_meta',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('asset_type', sa.String(length=20), nullable=False),
    sa.Column('exchange', sa.String(length=10), nullable=False),
    sa.Column('list_date', sa.Date(), nullable=True),
    sa.Column('delist_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index('idx_asset_meta_exchange', 'asset_meta', ['exchange'], unique=False)
    op.create_index('idx_asset_meta_status', 'asset_meta', ['status'], unique=False)
    op.create_index('idx_asset_meta_type', 'asset_meta', ['asset_type'], unique=False)
    op.create_table('fundamental_indicators',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('report_type', sa.String(length=10), nullable=True),
    sa.Column('pe_ratio', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('pb_ratio', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('ps_ratio', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('ev_ebitda', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('roe', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('roa', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('gross_margin', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('net_margin', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('operating_margin', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('revenue_growth_yoy', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('profit_growth_yoy', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('eps_growth_yoy', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('operating_cash_flow', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('free_cash_flow', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('cash_flow_per_share', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('debt_to_equity', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('current_ratio', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('quick_ratio', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('eps', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('bvps', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('dividend_yield', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('code', 'report_date')
    )
    op.create_index('idx_fund_ind_code', 'fundamental_indicators', ['code'], unique=False)
    op.create_index('idx_fund_ind_date', 'fundamental_indicators', ['report_date'], unique=False)
    op.create_table('index_constituents',
    sa.Column('index_code', sa.String(length=20), nullable=False),
    sa.Column('stock_code', sa.String(length=20), nullable=False),
    sa.Column('weight', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('expire_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('index_code', 'stock_code', 'effective_date')
    )
    op.create_index('idx_constituents_effective', 'index_constituents', ['effective_date'], unique=False)
    op.create_index('idx_constituents_index', 'index_constituents', ['index_code'], unique=False)
    op.create_index('idx_constituents_stock', 'index_constituents', ['stock_code'], unique=False)
    op.create_table('indicator_etf',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('iopv', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('discount_rate', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('unit_total', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('tracking_error', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('code', 'date')
    )
    op.create_index('idx_indicator_etf_code', 'indicator_etf', ['code'], unique=False)
    op.create_index('idx_indicator_etf_date', 'indicator_etf', ['date'], unique=False)
    op.create_table('indicator_valuation',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('pe_ttm', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('pb_mrq', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('ps_ttm', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('pcf_ncf_ttm', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('total_mv', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('circ_mv', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('is_st', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('code', 'date')
    )
    op.create_index('idx_indicator_valuation_code', 'indicator_valuation', ['code'], unique=False)
    op.create_index('idx_indicator_valuation_date', 'indicator_valuation', ['date'], unique=False)
    op.create_table('industry_classification',
    sa.Column('industry_code', sa.String(length=20), nullable=False),
    sa.Column('industry_name', sa.String(length=100), nullable=False),
    sa.Column('industry_level', sa.Integer(), nullable=False),
    sa.Column('parent_code', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('industry_code')
    )
    op.create_index('idx_industry_level', 'industry_classification', ['industry_level'], unique=False)
    op.create_index('idx_industry_parent', 'industry_classification', ['parent_code'], unique=False)
    op.create_table('market_daily',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('high', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('low', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('close', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('preclose', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('turn', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('pct_chg', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('trade_status', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('code', 'date')
    )
    op.create_index('idx_market_daily_code', 'market_daily', ['code'], unique=False)
    op.create_index('idx_market_daily_date', 'market_daily', ['date'], unique=False)
    op.create_table('market_regime',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('regime', sa.String(length=20), nullable=False),
    sa.Column('regime_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('total_stocks', sa.Integer(), nullable=False),
    sa.Column('up_count', sa.Integer(), nullable=False),
    sa.Column('down_count', sa.Integer(), nullable=False),
    sa.Column('limit_up_count', sa.Integer(), nullable=False),
    sa.Column('limit_down_count', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('avg_turnover', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('sh_index', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('sz_index', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('hs300_index', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('sh_above_ma20', sa.Boolean(), nullable=True),
    sa.Column('sh_above_ma60', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_index('idx_market_regime_regime', 'market_regime', ['regime'], unique=False)
    op.create_table('stock_classification_snapshot',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('board', sa.String(length=20), nullable=True),
    sa.Column('structural_type', sa.String(length=20), nullable=True),
    sa.Column('is_st', sa.Boolean(), nullable=False),
    sa.Column('is_new', sa.Boolean(), nullable=False),
    sa.Column('industry_l1', sa.String(length=50), nullable=True),
    sa.Column('industry_l2', sa.String(length=50), nullable=True),
    sa.Column('industry_l3', sa.String(length=50), nullable=True),
    sa.Column('size_category', sa.String(length=20), nullable=True),
    sa.Column('vol_category', sa.String(length=20), nullable=True),
    sa.Column('turnover_category', sa.String(length=20), nullable=True),
    sa.Column('value_category', sa.String(length=20), nullable=True),
    sa.Column('is_institutional', sa.Boolean(), nullable=False),
    sa.Column('is_northbound_heavy', sa.Boolean(), nullable=False),
    sa.Column('market_regime', sa.String(length=20), nullable=True),
    sa.Column('classification_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('code', 'date')
    )
    op.create_index('idx_snapshot_board', 'stock_classification_snapshot', ['board'], unique=False)
    op.create_index('idx_snapshot_code', 'stock_classification_snapshot', ['code'], unique=False)
    op.create_index('idx_snapshot_date', 'stock_classification_snapshot', ['date'], unique=False)
    op.create_index('idx_snapshot_industry_l1', 'stock_classification_snapshot', ['industry_l1'], unique=False)
    op.create_index('idx_snapshot_regime', 'stock_classification_snapshot', ['market_regime'], unique=False)
    op.create_index('idx_snapshot_size', 'stock_classification_snapshot', ['size_category'], unique=False)
    op.create_table('stock_industry_mapping',
    sa.Column('stock_code', sa.String(length=20), nullable=False),
    sa.Column('industry_code', sa.String(length=20), nullable=False),
    sa.Column('classification_system', sa.String(length=20), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('expire_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('stock_code', 'industry_code', 'classification_system', 'effective_date')
    )
    op.create_index('idx_industry_mapping_code', 'stock_industry_mapping', ['stock_code'], unique=False)
    op.create_index('idx_industry_mapping_effective', 'stock_industry_mapping', ['effective_date'], unique=False)
    op.create_index('idx_industry_mapping_industry', 'stock_industry_mapping', ['industry_code'], unique=False)
    op.create_index('idx_industry_mapping_system', 'stock_industry_mapping', ['classification_system'], unique=False)
    op.create_table('stock_microstructure',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('fund_holding_ratio', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('fund_holding_change', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('northbound_holding_ratio', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('northbound_holding_change', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('is_institutional', sa.Boolean(), nullable=False),
    sa.Column('is_northbound_heavy', sa.Boolean(), nullable=False),
    sa.Column('is_retail_hot', sa.Boolean(), nullable=False),
    sa.Column('is_main_controlled', sa.Boolean(), nullable=False),
    sa.Column('dragon_tiger_count_20d', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('code', 'date')
    )
    op.create_index('idx_microstructure_code', 'stock_microstructure', ['code'], unique=False)
    op.create_index('idx_microstructure_date', 'stock_microstructure', ['date'], unique=False)
    op.create_index('idx_microstructure_institutional', 'stock_microstructure', ['is_institutional'], unique=False)
    op.create_index('idx_microstructure_northbound', 'stock_microstructure', ['is_northbound_heavy'], unique=False)
    op.create_table('stock_style_exposure',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('market_cap', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('size_rank', sa.Integer(), nullable=True),
    sa.Column('size_percentile', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('size_category', sa.String(length=20), nullable=True),
    sa.Column('volatility_20d', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('vol_rank', sa.Integer(), nullable=True),
    sa.Column('vol_percentile', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('vol_category', sa.String(length=20), nullable=True),
    sa.Column('avg_turnover_20d', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('turnover_rank', sa.Integer(), nullable=True),
    sa.Column('turnover_percentile', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('turnover_category', sa.String(length=20), nullable=True),
    sa.Column('ep_ratio', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('bp_ratio', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('value_rank', sa.Integer(), nullable=True),
    sa.Column('value_percentile', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('value_category', sa.String(length=20), nullable=True),
    sa.Column('momentum_20d', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('momentum_60d', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('momentum_rank', sa.Integer(), nullable=True),
    sa.Column('momentum_percentile', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('code', 'date')
    )
    op.create_index('idx_style_exposure_code', 'stock_style_exposure', ['code'], unique=False)
    op.create_index('idx_style_exposure_date', 'stock_style_exposure', ['date'], unique=False)
    op.create_index('idx_style_exposure_size_cat', 'stock_style_exposure', ['size_category'], unique=False)
    op.create_index('idx_style_exposure_vol_cat', 'stock_style_exposure', ['vol_category'], unique=False)
    op.create_table('technical_indicators',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('ma_5', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('ma_10', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('ma_20', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('ma_60', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('ma_120', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('ma_250', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('ema_12', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('ema_26', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('macd_dif', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('macd_dea', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('macd_hist', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('rsi_6', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('rsi_12', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('rsi_24', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('kdj_k', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('kdj_d', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('kdj_j', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('boll_upper', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('boll_middle', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('boll_lower', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('vol_ma_5', sa.BigInteger(), nullable=True),
    sa.Column('vol_ma_10', sa.BigInteger(), nullable=True),
    sa.Column('atr_14', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('obv', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('code', 'date')
    )
    op.create_index('idx_tech_ind_code', 'technical_indicators', ['code'], unique=False)
    op.create_index('idx_tech_ind_date', 'technical_indicators', ['date'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('salt', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('api_key_hash', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_api_key_hash'), 'users', ['api_key_hash'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('etf_profile',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('etf_type', sa.String(length=20), nullable=True),
    sa.Column('underlying_index_code', sa.String(length=20), nullable=True),
    sa.Column('underlying_index_name', sa.String(length=100), nullable=True),
    sa.Column('fund_company', sa.String(length=100), nullable=True),
    sa.Column('management_fee', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('custody_fee', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('fund_size', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['code'], ['asset_meta.code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index('idx_etf_profile_company', 'etf_profile', ['fund_company'], unique=False)
    op.create_index('idx_etf_profile_index', 'etf_profile', ['underlying_index_code'], unique=False)
    op.create_index('idx_etf_profile_type', 'etf_profile', ['etf_type'], unique=False)
    op.create_table('stock_pool_combinations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('combination_expr', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('stock_count', sa.Integer(), nullable=False),
    sa.Column('last_evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pool_combinations_user', 'stock_pool_combinations', ['user_id'], unique=False)
    op.create_table('stock_pools',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('pool_type', sa.String(length=20), nullable=False),
    sa.Column('predefined_key', sa.String(length=50), nullable=True),
    sa.Column('filter_expression', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('stock_count', sa.Integer(), nullable=False),
    sa.Column('last_evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("pool_type IN ('predefined', 'custom', 'dynamic')", name='valid_pool_type'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_stock_pools_predefined', 'stock_pools', ['predefined_key'], unique=False)
    op.create_index('idx_stock_pools_public', 'stock_pools', ['is_public'], unique=False)
    op.create_index('idx_stock_pools_type', 'stock_pools', ['pool_type'], unique=False)
    op.create_index('idx_stock_pools_user', 'stock_pools', ['user_id'], unique=False)
    op.create_table('stock_profile',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('sw_industry_l1', sa.String(length=50), nullable=True),
    sa.Column('sw_industry_l2', sa.String(length=50), nullable=True),
    sa.Column('sw_industry_l3', sa.String(length=50), nullable=True),
    sa.Column('concepts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('province', sa.String(length=50), nullable=True),
    sa.Column('total_shares', sa.BigInteger(), nullable=True),
    sa.Column('float_shares', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['code'], ['asset_meta.code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index('idx_stock_profile_province', 'stock_profile', ['province'], unique=False)
    op.create_index('idx_stock_profile_sw_l1', 'stock_profile', ['sw_industry_l1'], unique=False)
    op.create_index('idx_stock_profile_sw_l2', 'stock_profile', ['sw_industry_l2'], unique=False)
    op.create_table('stock_structural_info',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('board', sa.String(length=20), nullable=False),
    sa.Column('structural_type', sa.String(length=20), nullable=False),
    sa.Column('price_limit_up', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('price_limit_down', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_st', sa.Boolean(), nullable=False),
    sa.Column('is_new', sa.Boolean(), nullable=False),
    sa.Column('is_suspended', sa.Boolean(), nullable=False),
    sa.Column('list_date', sa.Date(), nullable=True),
    sa.Column('st_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['code'], ['asset_meta.code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index('idx_structural_board', 'stock_structural_info', ['board'], unique=False)
    op.create_index('idx_structural_is_st', 'stock_structural_info', ['is_st'], unique=False)
    op.create_index('idx_structural_type', 'stock_structural_info', ['structural_type'], unique=False)
    op.create_table('strategies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('strategy_type', sa.String(length=50), nullable=True),
    sa.Column('indicators_used', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_validated', sa.Boolean(), nullable=False),
    sa.Column('validation_error', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('execution_mode', sa.String(length=20), nullable=False),
    sa.Column('risk_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('broker_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_strategies_active', 'strategies', ['is_active'], unique=False)
    op.create_index('idx_strategies_type', 'strategies', ['strategy_type'], unique=False)
    op.create_index('idx_strategies_user', 'strategies', ['user_id'], unique=False)
    op.create_index('idx_strategies_user_name_version', 'strategies', ['user_id', 'name', 'version'], unique=True)
    op.create_table('backtest_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('strategy_ids', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('stock_codes', postgresql.ARRAY(sa.String(length=20)), nullable=False),
    sa.Column('stock_filter', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pool_id', sa.UUID(), nullable=True),
    sa.Column('pool_combination_id', sa.UUID(), nullable=True),
    sa.Column('pool_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='池执行时的快照 {pool_id, pool_name, stock_count, evaluated_at}'),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('initial_capital', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('commission_rate', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('slippage', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('position_sizing', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='backteststatus', native_enum=False), nullable=False),
    sa.Column('progress', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('arq_job_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_backtests', sa.Integer(), nullable=False),
    sa.Column('successful_backtests', sa.Integer(), nullable=False),
    sa.Column('failed_backtests', sa.Integer(), nullable=False),
    sa.Column('strategy_snapshots', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='策略执行时的完整快照 {strategy_id: {name, code, ...}}'),
    sa.ForeignKeyConstraint(['pool_combination_id'], ['stock_pool_combinations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pool_id'], ['stock_pools.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_backtest_jobs_created', 'backtest_jobs', ['created_at'], unique=False)
    op.create_index('idx_backtest_jobs_status', 'backtest_jobs', ['status'], unique=False)
    op.create_index('idx_backtest_jobs_user', 'backtest_jobs', ['user_id'], unique=False)
    op.create_table('stock_pool_members',
    sa.Column('pool_id', sa.UUID(), nullable=False),
    sa.Column('stock_code', sa.String(length=20), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('added_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['pool_id'], ['stock_pools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pool_id', 'stock_code')
    )
    op.create_index('idx_pool_members_stock', 'stock_pool_members', ['stock_code'], unique=False)
    op.create_table('strategy_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('strategy_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('change_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_strategy_versions_strategy_version', 'strategy_versions', ['strategy_id', 'version'], unique=True)
    op.create_table('backtest_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('strategy_id', sa.UUID(), nullable=False),
    sa.Column('stock_code', sa.String(length=20), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_return', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('annual_return', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('sharpe_ratio', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('sortino_ratio', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('calmar_ratio', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('max_drawdown', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('max_drawdown_duration', sa.Integer(), nullable=True),
    sa.Column('volatility', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('var_95', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('cvar_95', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('beta', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('alpha', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('total_trades', sa.Integer(), nullable=True),
    sa.Column('winning_trades', sa.Integer(), nullable=True),
    sa.Column('losing_trades', sa.Integer(), nullable=True),
    sa.Column('win_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('avg_win', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('avg_loss', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('profit_factor', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('avg_trade_duration', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('final_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('peak_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('monthly_returns', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='backteststatus', native_enum=False), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['backtest_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_backtest_results_job', 'backtest_results', ['job_id'], unique=False)
    op.create_index('idx_backtest_results_job_strategy_stock', 'backtest_results', ['job_id', 'strategy_id', 'stock_code'], unique=True)
    op.create_index('idx_backtest_results_sharpe', 'backtest_results', ['sharpe_ratio'], unique=False)
    op.create_index('idx_backtest_results_stock', 'backtest_results', ['stock_code'], unique=False)
    op.create_index('idx_backtest_results_strategy', 'backtest_results', ['strategy_id'], unique=False)
    op.create_table('backtest_equity',
    sa.Column('result_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('cash', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('position_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('drawdown', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('daily_return', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.ForeignKeyConstraint(['result_id'], ['backtest_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('result_id', 'date')
    )
    op.create_index('idx_backtest_equity_date', 'backtest_equity', ['date'], unique=False)
    op.create_index('idx_backtest_equity_result', 'backtest_equity', ['result_id'], unique=False)
    op.create_table('backtest_trades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('result_id', sa.UUID(), nullable=False),
    sa.Column('stock_code', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('exit_date', sa.Date(), nullable=True),
    sa.Column('exit_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('pnl', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('commission', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('net_pnl', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('pnl_percent', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('bars_held', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['result_id'], ['backtest_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_backtest_trades_entry_date', 'backtest_trades', ['entry_date'], unique=False)
    op.create_index('idx_backtest_trades_result', 'backtest_trades', ['result_id'], unique=False)
    op.create_index('idx_backtest_trades_stock', 'backtest_trades', ['stock_code'], unique=False)
    # ### end Alembic commands ###

    # ===========================================================================
    # TimescaleDB Hypertables
    # ===========================================================================
    # Create hypertables for time-series data
    op.execute("""
        SELECT create_hypertable('market_daily', 'date',
            chunk_time_interval => INTERVAL '1 month',
            if_not_exists => TRUE
        );
    """)
    op.execute("""
        SELECT create_hypertable('indicator_valuation', 'date',
            chunk_time_interval => INTERVAL '1 month',
            if_not_exists => TRUE
        );
    """)
    op.execute("""
        SELECT create_hypertable('indicator_etf', 'date',
            chunk_time_interval => INTERVAL '1 month',
            if_not_exists => TRUE
        );
    """)
    op.execute("""
        SELECT create_hypertable('adjust_factor', 'divid_operate_date',
            chunk_time_interval => INTERVAL '1 year',
            if_not_exists => TRUE
        );
    """)
    op.execute("""
        SELECT create_hypertable('technical_indicators', 'date',
            chunk_time_interval => INTERVAL '1 month',
            if_not_exists => TRUE
        );
    """)
    op.execute("""
        SELECT create_hypertable('fundamental_indicators', 'report_date',
            chunk_time_interval => INTERVAL '3 months',
            if_not_exists => TRUE
        );
    """)
    op.execute("""
        SELECT create_hypertable('stock_style_exposure', 'date',
            chunk_time_interval => INTERVAL '1 month',
            if_not_exists => TRUE
        );
    """)
    op.execute("""
        SELECT create_hypertable('stock_microstructure', 'date',
            chunk_time_interval => INTERVAL '1 month',
            if_not_exists => TRUE
        );
    """)
    op.execute("""
        SELECT create_hypertable('stock_classification_snapshot', 'date',
            chunk_time_interval => INTERVAL '1 month',
            if_not_exists => TRUE
        );
    """)

    # ===========================================================================
    # Seed Data: Default User
    # ===========================================================================
    op.execute("""
        INSERT INTO users (id, email, username, password_hash, salt, is_active, is_admin)
        VALUES (
            '00000000-0000-0000-0000-000000000001',
            'demo@quant.local',
            'demo',
            'not_a_real_hash',
            'not_a_real_salt',
            TRUE,
            FALSE
        ) ON CONFLICT DO NOTHING;
    """)

    # ===========================================================================
    # Seed Data: Predefined ETF Pools
    # ===========================================================================
    etf_pools = [
        ('etf_all', 'All ETFs', 'All ETF products'),
        ('etf_sh', 'Shanghai ETFs', 'ETFs listed on Shanghai Stock Exchange'),
        ('etf_sz', 'Shenzhen ETFs', 'ETFs listed on Shenzhen Stock Exchange'),
        ('etf_broad', 'Broad-based ETFs', 'Broad market index ETFs'),
        ('etf_sector', 'Sector ETFs', 'Industry and sector ETFs'),
        ('etf_theme', 'Thematic ETFs', 'Thematic ETFs'),
        ('etf_cross_border', 'Cross-border ETFs', 'Cross-border and international ETFs'),
        ('etf_commodity', 'Commodity ETFs', 'Commodity and gold ETFs'),
    ]

    for key, name, desc in etf_pools:
        op.execute(f"""
            INSERT INTO stock_pools (id, user_id, name, description, pool_type, predefined_key, is_public, is_system, stock_count)
            VALUES (
                gen_random_uuid(),
                '00000000-0000-0000-0000-000000000001',
                '{name}',
                '{desc}',
                'predefined',
                '{key}',
                TRUE,
                TRUE,
                0
            ) ON CONFLICT DO NOTHING;
        """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_backtest_trades_stock', table_name='backtest_trades')
    op.drop_index('idx_backtest_trades_result', table_name='backtest_trades')
    op.drop_index('idx_backtest_trades_entry_date', table_name='backtest_trades')
    op.drop_table('backtest_trades')
    op.drop_index('idx_backtest_equity_result', table_name='backtest_equity')
    op.drop_index('idx_backtest_equity_date', table_name='backtest_equity')
    op.drop_table('backtest_equity')
    op.drop_index('idx_backtest_results_strategy', table_name='backtest_results')
    op.drop_index('idx_backtest_results_stock', table_name='backtest_results')
    op.drop_index('idx_backtest_results_sharpe', table_name='backtest_results')
    op.drop_index('idx_backtest_results_job_strategy_stock', table_name='backtest_results')
    op.drop_index('idx_backtest_results_job', table_name='backtest_results')
    op.drop_table('backtest_results')
    op.drop_index('idx_strategy_versions_strategy_version', table_name='strategy_versions')
    op.drop_table('strategy_versions')
    op.drop_index('idx_pool_members_stock', table_name='stock_pool_members')
    op.drop_table('stock_pool_members')
    op.drop_index('idx_backtest_jobs_user', table_name='backtest_jobs')
    op.drop_index('idx_backtest_jobs_status', table_name='backtest_jobs')
    op.drop_index('idx_backtest_jobs_created', table_name='backtest_jobs')
    op.drop_table('backtest_jobs')
    op.drop_index('idx_strategies_user_name_version', table_name='strategies')
    op.drop_index('idx_strategies_user', table_name='strategies')
    op.drop_index('idx_strategies_type', table_name='strategies')
    op.drop_index('idx_strategies_active', table_name='strategies')
    op.drop_table('strategies')
    op.drop_index('idx_structural_type', table_name='stock_structural_info')
    op.drop_index('idx_structural_is_st', table_name='stock_structural_info')
    op.drop_index('idx_structural_board', table_name='stock_structural_info')
    op.drop_table('stock_structural_info')
    op.drop_index('idx_stock_profile_sw_l2', table_name='stock_profile')
    op.drop_index('idx_stock_profile_sw_l1', table_name='stock_profile')
    op.drop_index('idx_stock_profile_province', table_name='stock_profile')
    op.drop_table('stock_profile')
    op.drop_index('idx_stock_pools_user', table_name='stock_pools')
    op.drop_index('idx_stock_pools_type', table_name='stock_pools')
    op.drop_index('idx_stock_pools_public', table_name='stock_pools')
    op.drop_index('idx_stock_pools_predefined', table_name='stock_pools')
    op.drop_table('stock_pools')
    op.drop_index('idx_pool_combinations_user', table_name='stock_pool_combinations')
    op.drop_table('stock_pool_combinations')
    op.drop_index('idx_etf_profile_type', table_name='etf_profile')
    op.drop_index('idx_etf_profile_index', table_name='etf_profile')
    op.drop_index('idx_etf_profile_company', table_name='etf_profile')
    op.drop_table('etf_profile')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_api_key_hash'), table_name='users')
    op.drop_table('users')
    op.drop_index('idx_tech_ind_date', table_name='technical_indicators')
    op.drop_index('idx_tech_ind_code', table_name='technical_indicators')
    op.drop_table('technical_indicators')
    op.drop_index('idx_style_exposure_vol_cat', table_name='stock_style_exposure')
    op.drop_index('idx_style_exposure_size_cat', table_name='stock_style_exposure')
    op.drop_index('idx_style_exposure_date', table_name='stock_style_exposure')
    op.drop_index('idx_style_exposure_code', table_name='stock_style_exposure')
    op.drop_table('stock_style_exposure')
    op.drop_index('idx_microstructure_northbound', table_name='stock_microstructure')
    op.drop_index('idx_microstructure_institutional', table_name='stock_microstructure')
    op.drop_index('idx_microstructure_date', table_name='stock_microstructure')
    op.drop_index('idx_microstructure_code', table_name='stock_microstructure')
    op.drop_table('stock_microstructure')
    op.drop_index('idx_industry_mapping_system', table_name='stock_industry_mapping')
    op.drop_index('idx_industry_mapping_industry', table_name='stock_industry_mapping')
    op.drop_index('idx_industry_mapping_effective', table_name='stock_industry_mapping')
    op.drop_index('idx_industry_mapping_code', table_name='stock_industry_mapping')
    op.drop_table('stock_industry_mapping')
    op.drop_index('idx_snapshot_size', table_name='stock_classification_snapshot')
    op.drop_index('idx_snapshot_regime', table_name='stock_classification_snapshot')
    op.drop_index('idx_snapshot_industry_l1', table_name='stock_classification_snapshot')
    op.drop_index('idx_snapshot_date', table_name='stock_classification_snapshot')
    op.drop_index('idx_snapshot_code', table_name='stock_classification_snapshot')
    op.drop_index('idx_snapshot_board', table_name='stock_classification_snapshot')
    op.drop_table('stock_classification_snapshot')
    op.drop_index('idx_market_regime_regime', table_name='market_regime')
    op.drop_table('market_regime')
    op.drop_index('idx_market_daily_date', table_name='market_daily')
    op.drop_index('idx_market_daily_code', table_name='market_daily')
    op.drop_table('market_daily')
    op.drop_index('idx_industry_parent', table_name='industry_classification')
    op.drop_index('idx_industry_level', table_name='industry_classification')
    op.drop_table('industry_classification')
    op.drop_index('idx_indicator_valuation_date', table_name='indicator_valuation')
    op.drop_index('idx_indicator_valuation_code', table_name='indicator_valuation')
    op.drop_table('indicator_valuation')
    op.drop_index('idx_indicator_etf_date', table_name='indicator_etf')
    op.drop_index('idx_indicator_etf_code', table_name='indicator_etf')
    op.drop_table('indicator_etf')
    op.drop_index('idx_constituents_stock', table_name='index_constituents')
    op.drop_index('idx_constituents_index', table_name='index_constituents')
    op.drop_index('idx_constituents_effective', table_name='index_constituents')
    op.drop_table('index_constituents')
    op.drop_index('idx_fund_ind_date', table_name='fundamental_indicators')
    op.drop_index('idx_fund_ind_code', table_name='fundamental_indicators')
    op.drop_table('fundamental_indicators')
    op.drop_index('idx_asset_meta_type', table_name='asset_meta')
    op.drop_index('idx_asset_meta_status', table_name='asset_meta')
    op.drop_index('idx_asset_meta_exchange', table_name='asset_meta')
    op.drop_table('asset_meta')
    op.drop_index('idx_adjust_factor_date', table_name='adjust_factor')
    op.drop_index('idx_adjust_factor_code', table_name='adjust_factor')
    op.drop_table('adjust_factor')
    # ### end Alembic commands ###
