"""add_stock_pool_tables

Revision ID: 6f64fd38d2fb
Revises: 0219bb2f37c2
Create Date: 2025-12-13 03:15:28.956938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6f64fd38d2fb'
down_revision: Union[str, Sequence[str], None] = '0219bb2f37c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('index_constituents',
    sa.Column('index_code', sa.String(length=20), nullable=False),
    sa.Column('stock_code', sa.String(length=20), nullable=False),
    sa.Column('weight', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('expire_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('index_code', 'stock_code', 'effective_date')
    )
    op.create_index('idx_constituents_effective', 'index_constituents', ['effective_date'], unique=False)
    op.create_index('idx_constituents_index', 'index_constituents', ['index_code'], unique=False)
    op.create_index('idx_constituents_stock', 'index_constituents', ['stock_code'], unique=False)
    op.create_table('stock_pool_combinations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('combination_expr', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('stock_count', sa.Integer(), nullable=False),
    sa.Column('last_evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pool_combinations_user', 'stock_pool_combinations', ['user_id'], unique=False)
    op.create_table('stock_pools',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('pool_type', sa.String(length=20), nullable=False),
    sa.Column('predefined_key', sa.String(length=50), nullable=True),
    sa.Column('filter_expression', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('stock_count', sa.Integer(), nullable=False),
    sa.Column('last_evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("pool_type IN ('predefined', 'custom', 'dynamic')", name='valid_pool_type'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_stock_pools_predefined', 'stock_pools', ['predefined_key'], unique=False)
    op.create_index('idx_stock_pools_public', 'stock_pools', ['is_public'], unique=False)
    op.create_index('idx_stock_pools_type', 'stock_pools', ['pool_type'], unique=False)
    op.create_index('idx_stock_pools_user', 'stock_pools', ['user_id'], unique=False)
    op.create_table('stock_pool_members',
    sa.Column('pool_id', sa.UUID(), nullable=False),
    sa.Column('stock_code', sa.String(length=20), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('added_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['pool_id'], ['stock_pools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pool_id', 'stock_code')
    )
    op.create_index('idx_pool_members_stock', 'stock_pool_members', ['stock_code'], unique=False)
    op.add_column('backtest_jobs', sa.Column('pool_id', sa.UUID(), nullable=True))
    op.add_column('backtest_jobs', sa.Column('pool_combination_id', sa.UUID(), nullable=True))
    op.add_column('backtest_jobs', sa.Column('pool_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='池执行时的快照 {pool_id, pool_name, stock_count, evaluated_at}'))
    op.create_foreign_key(None, 'backtest_jobs', 'stock_pools', ['pool_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'backtest_jobs', 'stock_pool_combinations', ['pool_combination_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###

    # Seed predefined stock pools
    op.execute("""
        INSERT INTO stock_pools (id, name, description, pool_type, predefined_key, is_public, is_system, stock_count)
        VALUES
            (gen_random_uuid(), '全部沪市', '上海证券交易所全部股票', 'predefined', 'sh_all', true, true, 0),
            (gen_random_uuid(), '全部深市', '深圳证券交易所全部股票', 'predefined', 'sz_all', true, true, 0),
            (gen_random_uuid(), '非ST股票', '排除ST和*ST股票', 'predefined', 'non_st', true, true, 0),
            (gen_random_uuid(), '主板股票', '沪深主板股票（60xxxx, 00xxxx）', 'predefined', 'main_board', true, true, 0),
            (gen_random_uuid(), '创业板', '创业板股票（30xxxx）', 'predefined', 'gem', true, true, 0),
            (gen_random_uuid(), '科创板', '科创板股票（688xxx）', 'predefined', 'star', true, true, 0)
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'backtest_jobs', type_='foreignkey')
    op.drop_constraint(None, 'backtest_jobs', type_='foreignkey')
    op.drop_column('backtest_jobs', 'pool_snapshot')
    op.drop_column('backtest_jobs', 'pool_combination_id')
    op.drop_column('backtest_jobs', 'pool_id')
    op.drop_index('idx_pool_members_stock', table_name='stock_pool_members')
    op.drop_table('stock_pool_members')
    op.drop_index('idx_stock_pools_user', table_name='stock_pools')
    op.drop_index('idx_stock_pools_type', table_name='stock_pools')
    op.drop_index('idx_stock_pools_public', table_name='stock_pools')
    op.drop_index('idx_stock_pools_predefined', table_name='stock_pools')
    op.drop_table('stock_pools')
    op.drop_index('idx_pool_combinations_user', table_name='stock_pool_combinations')
    op.drop_table('stock_pool_combinations')
    op.drop_index('idx_constituents_stock', table_name='index_constituents')
    op.drop_index('idx_constituents_index', table_name='index_constituents')
    op.drop_index('idx_constituents_effective', table_name='index_constituents')
    op.drop_table('index_constituents')
    # ### end Alembic commands ###
