"""add_strategy_snapshots_to_backtest_jobs

Revision ID: 0219bb2f37c2
Revises: 63f9700ffb44
Create Date: 2025-12-12 11:55:16.361078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0219bb2f37c2'
down_revision: Union[str, Sequence[str], None] = '63f9700ffb44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backtest_jobs', sa.Column('strategy_snapshots', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='策略执行时的完整快照 {strategy_id: {name, code, ...}}'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('backtest_jobs', 'strategy_snapshots')
    # ### end Alembic commands ###
