"""add stock tracker tables

Revision ID: 118b694c0126
Revises: h8i9j0k1l2m3
Create Date: 2026-03-26 12:26:09.792166

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "118b694c0126"
down_revision: Union[str, Sequence[str], None] = "h8i9j0k1l2m3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "baostock_minute_cache",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("ts_code", sa.String(length=20), nullable=False),
        sa.Column("trade_date", sa.Date(), nullable=False),
        sa.Column("frequency", sa.String(length=10), nullable=False),
        sa.Column("candles", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ts_code", "trade_date", "frequency", name="uq_baostock_minute_cache"),
    )
    op.create_index(
        "idx_baostock_cache_code_date",
        "baostock_minute_cache",
        ["ts_code", "trade_date"],
        unique=False,
    )
    op.create_table(
        "stock_tracks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("ts_code", sa.String(length=20), nullable=False),
        sa.Column("stock_name", sa.String(length=100), nullable=True),
        sa.Column("watch_reason", sa.Text(), nullable=True),
        sa.Column("sector", sa.String(length=100), nullable=True),
        sa.Column("tags", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ts_code"),
    )
    op.create_index("idx_stock_tracks_active", "stock_tracks", ["is_active"], unique=False)
    op.create_index("idx_stock_tracks_ts_code", "stock_tracks", ["ts_code"], unique=False)
    op.create_table(
        "track_daily_entries",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("track_id", sa.UUID(), nullable=False),
        sa.Column("trade_date", sa.Date(), nullable=False),
        sa.Column("ts_code", sa.String(length=20), nullable=False),
        sa.Column("open", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("high", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("low", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("close", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("pre_close", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("volume", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("pct_chg", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.Column("pattern", sa.String(length=10), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("mood", sa.String(length=20), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["track_id"], ["stock_tracks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("track_id", "trade_date", name="uq_track_daily_entry"),
    )
    op.create_index(
        "idx_track_daily_entries_date", "track_daily_entries", ["trade_date"], unique=False
    )
    op.create_index(
        "idx_track_daily_entries_track", "track_daily_entries", ["track_id"], unique=False
    )
    op.create_index(
        "idx_track_daily_entries_ts_code", "track_daily_entries", ["ts_code"], unique=False
    )
    op.create_table(
        "daily_situation_scores",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("entry_id", sa.UUID(), nullable=False),
        sa.Column("scores", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("total_score", sa.SmallInteger(), nullable=False),
        sa.Column("market_label", sa.String(length=20), nullable=True),
        sa.Column("sector_label", sa.String(length=20), nullable=True),
        sa.Column("stock_label", sa.String(length=20), nullable=True),
        sa.Column("decision", sa.String(length=20), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["entry_id"], ["track_daily_entries.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("entry_id"),
    )
    op.create_index(
        "idx_daily_situation_entry", "daily_situation_scores", ["entry_id"], unique=False
    )
    op.create_table(
        "daily_sketch_points",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("entry_id", sa.UUID(), nullable=False),
        sa.Column("key_points", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("auto_pattern", sa.String(length=10), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["entry_id"], ["track_daily_entries.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("entry_id"),
    )
    op.create_index("idx_daily_sketch_entry", "daily_sketch_points", ["entry_id"], unique=False)
    op.create_table(
        "trade_operations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("entry_id", sa.UUID(), nullable=False),
        sa.Column("op_type", sa.String(length=20), nullable=False),
        sa.Column("op_time", sa.Time(), nullable=True),
        sa.Column("price", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=True),
        sa.Column("emotion", sa.String(length=50), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("op_type IN ('buy', 'sell', 'add', 'reduce')", name="valid_op_type"),
        sa.ForeignKeyConstraint(["entry_id"], ["track_daily_entries.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_trade_operations_entry", "trade_operations", ["entry_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_trade_operations_entry", table_name="trade_operations")
    op.drop_table("trade_operations")
    op.drop_index("idx_daily_sketch_entry", table_name="daily_sketch_points")
    op.drop_table("daily_sketch_points")
    op.drop_index("idx_daily_situation_entry", table_name="daily_situation_scores")
    op.drop_table("daily_situation_scores")
    op.drop_index("idx_track_daily_entries_ts_code", table_name="track_daily_entries")
    op.drop_index("idx_track_daily_entries_track", table_name="track_daily_entries")
    op.drop_index("idx_track_daily_entries_date", table_name="track_daily_entries")
    op.drop_table("track_daily_entries")
    op.drop_index("idx_stock_tracks_ts_code", table_name="stock_tracks")
    op.drop_index("idx_stock_tracks_active", table_name="stock_tracks")
    op.drop_table("stock_tracks")
    op.drop_index("idx_baostock_cache_code_date", table_name="baostock_minute_cache")
    op.drop_table("baostock_minute_cache")
    # ### end Alembic commands ###
