"""initial schema

Revision ID: 642576ce6ede
Revises: 
Create Date: 2025-12-05 14:02:10.026534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '642576ce6ede'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adjust_factor',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('divid_operate_date', sa.Date(), nullable=True),
    sa.Column('fore_adjust_factor', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('back_adjust_factor', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('adjust_factor', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_adjust_factor_code_date', 'adjust_factor', ['code', 'divid_operate_date'], unique=True)
    op.create_index(op.f('ix_adjust_factor_code'), 'adjust_factor', ['code'], unique=False)
    op.create_table('daily_k_data',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('open', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('high', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('low', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('close', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('preclose', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('turn', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('trade_status', sa.Integer(), nullable=True),
    sa.Column('pct_chg', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('pe_ttm', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('pb_mrq', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('ps_ttm', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('pcf_ncf_ttm', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('is_st', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_daily_k_code_date', 'daily_k_data', ['code', 'date'], unique=True)
    op.create_index('idx_daily_k_date', 'daily_k_data', ['date'], unique=False)
    op.create_index(op.f('ix_daily_k_data_code'), 'daily_k_data', ['code'], unique=False)
    op.create_table('fundamental_indicators',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('report_type', sa.String(length=10), nullable=True),
    sa.Column('pe_ratio', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('pb_ratio', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('ps_ratio', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('ev_ebitda', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('roe', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('roa', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('gross_margin', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('net_margin', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('operating_margin', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('revenue_growth_yoy', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('profit_growth_yoy', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('eps_growth_yoy', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('operating_cash_flow', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('free_cash_flow', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('cash_flow_per_share', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('debt_to_equity', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('current_ratio', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('quick_ratio', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('eps', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('bvps', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('dividend_yield', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fund_ind_code', 'fundamental_indicators', ['code'], unique=False)
    op.create_index('idx_fund_ind_code_date', 'fundamental_indicators', ['code', 'report_date'], unique=True)
    op.create_table('stock_basic',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('code_name', sa.String(length=100), nullable=True),
    sa.Column('ipo_date', sa.Date(), nullable=True),
    sa.Column('out_date', sa.Date(), nullable=True),
    sa.Column('stock_type', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('exchange', sa.String(length=10), nullable=True),
    sa.Column('sector', sa.String(length=50), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index('idx_stock_basic_exchange', 'stock_basic', ['exchange'], unique=False)
    op.create_index('idx_stock_basic_sector', 'stock_basic', ['sector'], unique=False)
    op.create_table('technical_indicators',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('ma_5', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('ma_10', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('ma_20', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('ma_60', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('ma_120', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('ma_250', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('ema_12', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('ema_26', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('macd_dif', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('macd_dea', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('macd_hist', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('rsi_6', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('rsi_12', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('rsi_24', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('kdj_k', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('kdj_d', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('kdj_j', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('boll_upper', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('boll_middle', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('boll_lower', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('vol_ma_5', sa.BigInteger(), nullable=True),
    sa.Column('vol_ma_10', sa.BigInteger(), nullable=True),
    sa.Column('atr_14', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('obv', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tech_ind_code_date', 'technical_indicators', ['code', 'date'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('salt', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('api_key_hash', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_api_key_hash'), 'users', ['api_key_hash'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('backtest_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('strategy_ids', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('stock_codes', postgresql.ARRAY(sa.String(length=20)), nullable=False),
    sa.Column('stock_filter', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('initial_capital', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('commission_rate', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('slippage', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('position_sizing', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='backteststatus'), nullable=False),
    sa.Column('progress', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('arq_job_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_backtests', sa.Integer(), nullable=False),
    sa.Column('successful_backtests', sa.Integer(), nullable=False),
    sa.Column('failed_backtests', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_backtest_jobs_created', 'backtest_jobs', ['created_at'], unique=False)
    op.create_index('idx_backtest_jobs_status', 'backtest_jobs', ['status'], unique=False)
    op.create_index('idx_backtest_jobs_user', 'backtest_jobs', ['user_id'], unique=False)
    op.create_table('strategies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('strategy_type', sa.String(length=50), nullable=True),
    sa.Column('indicators_used', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_validated', sa.Boolean(), nullable=False),
    sa.Column('validation_error', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('execution_mode', sa.String(length=20), nullable=False),
    sa.Column('risk_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('broker_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_strategies_active', 'strategies', ['is_active'], unique=False)
    op.create_index('idx_strategies_type', 'strategies', ['strategy_type'], unique=False)
    op.create_index('idx_strategies_user', 'strategies', ['user_id'], unique=False)
    op.create_index('idx_strategies_user_name_version', 'strategies', ['user_id', 'name', 'version'], unique=True)
    op.create_table('backtest_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('strategy_id', sa.UUID(), nullable=False),
    sa.Column('stock_code', sa.String(length=20), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_return', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('annual_return', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('sharpe_ratio', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('sortino_ratio', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('calmar_ratio', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('max_drawdown', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('max_drawdown_duration', sa.Integer(), nullable=True),
    sa.Column('volatility', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('var_95', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('cvar_95', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('beta', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('alpha', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('total_trades', sa.Integer(), nullable=True),
    sa.Column('winning_trades', sa.Integer(), nullable=True),
    sa.Column('losing_trades', sa.Integer(), nullable=True),
    sa.Column('win_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('avg_win', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('avg_loss', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('profit_factor', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('avg_trade_duration', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('final_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('peak_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('equity_curve', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('trades', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('monthly_returns', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='backteststatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['backtest_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_backtest_results_job', 'backtest_results', ['job_id'], unique=False)
    op.create_index('idx_backtest_results_job_strategy_stock', 'backtest_results', ['job_id', 'strategy_id', 'stock_code'], unique=True)
    op.create_index('idx_backtest_results_sharpe', 'backtest_results', ['sharpe_ratio'], unique=False)
    op.create_index('idx_backtest_results_stock', 'backtest_results', ['stock_code'], unique=False)
    op.create_index('idx_backtest_results_strategy', 'backtest_results', ['strategy_id'], unique=False)
    op.create_table('strategy_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('strategy_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('change_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_strategy_versions_strategy_version', 'strategy_versions', ['strategy_id', 'version'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_strategy_versions_strategy_version', table_name='strategy_versions')
    op.drop_table('strategy_versions')
    op.drop_index('idx_backtest_results_strategy', table_name='backtest_results')
    op.drop_index('idx_backtest_results_stock', table_name='backtest_results')
    op.drop_index('idx_backtest_results_sharpe', table_name='backtest_results')
    op.drop_index('idx_backtest_results_job_strategy_stock', table_name='backtest_results')
    op.drop_index('idx_backtest_results_job', table_name='backtest_results')
    op.drop_table('backtest_results')
    op.drop_index('idx_strategies_user_name_version', table_name='strategies')
    op.drop_index('idx_strategies_user', table_name='strategies')
    op.drop_index('idx_strategies_type', table_name='strategies')
    op.drop_index('idx_strategies_active', table_name='strategies')
    op.drop_table('strategies')
    op.drop_index('idx_backtest_jobs_user', table_name='backtest_jobs')
    op.drop_index('idx_backtest_jobs_status', table_name='backtest_jobs')
    op.drop_index('idx_backtest_jobs_created', table_name='backtest_jobs')
    op.drop_table('backtest_jobs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_api_key_hash'), table_name='users')
    op.drop_table('users')
    op.drop_index('idx_tech_ind_code_date', table_name='technical_indicators')
    op.drop_table('technical_indicators')
    op.drop_index('idx_stock_basic_sector', table_name='stock_basic')
    op.drop_index('idx_stock_basic_exchange', table_name='stock_basic')
    op.drop_table('stock_basic')
    op.drop_index('idx_fund_ind_code_date', table_name='fundamental_indicators')
    op.drop_index('idx_fund_ind_code', table_name='fundamental_indicators')
    op.drop_table('fundamental_indicators')
    op.drop_index(op.f('ix_daily_k_data_code'), table_name='daily_k_data')
    op.drop_index('idx_daily_k_date', table_name='daily_k_data')
    op.drop_index('idx_daily_k_code_date', table_name='daily_k_data')
    op.drop_table('daily_k_data')
    op.drop_index(op.f('ix_adjust_factor_code'), table_name='adjust_factor')
    op.drop_index('idx_adjust_factor_code_date', table_name='adjust_factor')
    op.drop_table('adjust_factor')
    # ### end Alembic commands ###
