"""add new field

Revision ID: a243d04a5545
Revises: 642576ce6ede
Create Date: 2025-12-05 07:56:19.970328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a243d04a5545'
down_revision: Union[str, None] = '642576ce6ede'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('adjust_factor', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('adjust_factor_code_divid_operate_date_key'), 'adjust_factor', type_='unique')
    op.drop_index(op.f('idx_adjust_factor_code'), table_name='adjust_factor')
    op.create_index('idx_adjust_factor_code_date', 'adjust_factor', ['code', 'divid_operate_date'], unique=True)
    op.create_index(op.f('ix_adjust_factor_code'), 'adjust_factor', ['code'], unique=False)
    op.alter_column('daily_k_data', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('daily_k_data_code_date_key'), 'daily_k_data', type_='unique')
    op.drop_index(op.f('idx_daily_k_code'), table_name='daily_k_data')
    op.create_index('idx_daily_k_code_date', 'daily_k_data', ['code', 'date'], unique=True)
    op.create_index(op.f('ix_daily_k_data_code'), 'daily_k_data', ['code'], unique=False)
    op.alter_column('fundamental_indicators', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('stock_basic', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('stock_basic', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index('idx_stock_basic_sector', 'stock_basic', ['sector'], unique=False)
    op.alter_column('technical_indicators', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.alter_column('technical_indicators', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_stock_basic_sector', table_name='stock_basic')
    op.alter_column('stock_basic', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('stock_basic', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('fundamental_indicators', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_daily_k_data_code'), table_name='daily_k_data')
    op.drop_index('idx_daily_k_code_date', table_name='daily_k_data')
    op.create_index(op.f('idx_daily_k_code'), 'daily_k_data', ['code'], unique=False)
    op.create_unique_constraint(op.f('daily_k_data_code_date_key'), 'daily_k_data', ['code', 'date'], postgresql_nulls_not_distinct=False)
    op.alter_column('daily_k_data', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_adjust_factor_code'), table_name='adjust_factor')
    op.drop_index('idx_adjust_factor_code_date', table_name='adjust_factor')
    op.create_index(op.f('idx_adjust_factor_code'), 'adjust_factor', ['code'], unique=False)
    op.create_unique_constraint(op.f('adjust_factor_code_divid_operate_date_key'), 'adjust_factor', ['code', 'divid_operate_date'], postgresql_nulls_not_distinct=False)
    op.alter_column('adjust_factor', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###
